QA_QUERY_PROMPTS = [
    "Answer directly based on the given passages. Do not include any reasoning or thought process.",
    "Provide a direct answer using only the information in the passages. No explanations or reasoning.",
    "Respond with the answer alone—no analysis, no steps, just the final answer from the passages.",
    "State the answer plainly based on the provided text. Omit all reasoning or commentary.",
    "Give the answer straight from the passages. Do not explain how you arrived at it.",
    "Only output the factual answer derived from the passages. Skip any thinking or justification.",
    "Answer immediately and solely based on the passages. No internal reasoning or elaboration.",
    "Return the correct answer as stated or implied in the text. Do not show your work.",
    "Based on the passages, give the answer without any additional explanation or thought process.",
    "Directly state what the passage indicates. Avoid reasoning, interpretation, or meta-commentary.",
    "Extract and output the answer verbatim or implicitly from the text. No reasoning allowed.",
    "Your response must be the answer only—nothing else. Use the passages as your sole source.",
    "Do not reason aloud. Just provide the answer that the passages support.",
    "Answer concisely and directly from the given information. Exclude all reasoning steps.",
    "From the passages, output only the answer. Never include how or why.",
    "The response should be the answer itself—no preamble, no logic, no extra words.",
    "Strictly answer based on the text. Do not describe your thinking process in any way.",
    "Give the answer as if quoting or inferring directly from the passage. No reasoning.",
    "Only the final answer is required. Base it on the passages and omit everything else.",
    "Respond with the answer alone, drawn exclusively from the passages. No thought process.",
    "Answer directly from the passage. No reasoning, no explanations.",
    "State only the answer supported by the text. Do not explain.",
    "Provide the answer and nothing else. Base it strictly on the passage.",
    "Respond with the factual answer only. Omit all reasoning or commentary.",
    "Give the answer as stated or implied in the passage. No extra words.",
    "Answer concisely using only the information provided. Skip all reasoning.",
    "Your response must be the answer alone — no preamble, no logic, no filler.",
    "Extract the answer directly. Do not describe how you know it.",
    "Return just the answer. Do not include your reasoning or assumptions.",
    "Based on the passage, what is the answer? State it plainly.",
    "Do not think out loud. Just give the correct answer from the text.",
    "Output the answer verbatim or by direct implication. No analysis allowed.",
    "The passage contains the answer. Provide it without elaboration.",
    "Answer in one phrase or sentence - only what the passage supports.",
    "No reasoning. No steps. Just the answer derived from the passage.",
    "Limit your response to the exact answer. Exclude all meta-content.",
    "Give a straight answer based on the text. Nothing else is required.",
    "Respond as if quoting the passage. Do not add reasoning or context.",
    "Only the final answer matters. Source it from the passage and stop.",
    "Do not explain, summarize, or rephrase—just state the answer.",
    "The correct response is in the passage. Output it and nothing more.",
    "Answer immediately and factually. No internal monologue or justification.",
    "Stick to the facts in the passage. Omit all reasoning or opinion.",
    "Your entire output should be the answer—no exceptions, no extras.",
    "From the passage, what is true? State it directly and stop.",
    "Provide the answer without any supporting rationale or thought process.",
    "Just the answer—clear, direct, and grounded in the given text.",
    "Answer the question directly based on the given passages. Do NOT repeat the question.",
]

CONTINUATION_PROMPTS = [
    "Continue this passage", "Please continue", "What comes next?", "Continue the text",
    "Keep going", "Please proceed with the continuation", "What follows?",
    "Continue this passage", "Please continue the following text",
    "Continue writing from where it left off", "What comes next in this passage?",
    "Continue this document", "Extend this content further",
]